# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Publish release to repositories

on:
  push:
    tags:
      - "*"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java & Gradle
        uses: stashymane/quick-gradle-action@main
        with:
          gradle-cache-key: ${{ secrets.GRADLE_ENCRYPTION_KEY }}

      - name: Publish on Maven repository
        run: ./gradlew publish
        env:
          ORG_GRADLE_PROJECT_repoUser: ${{ secrets.REPO_USER }}
          ORG_GRADLE_PROJECT_repoToken: ${{ secrets.REPO_TOKEN }}
